micronaut:
  application:
    name: casaDoCodigo

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/casa_do_codigo_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: mysecret
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
